baseURL = "http://devtty.com/"
locale = "en-gb"
defaultContentLanguage = "en"
title = "devtty"
theme = 'LoveIt'

languageCode = "en"#
languageName = "English"

copyright = "devtty"

[params]
title = "devtty"
rss = true
description = "**Hiya!** I'm Denis - currently software engineer and specialized on web applications and IT security. <br><br>A private travel blog is available at www.renning.de"
mainSectionTitle = "Blog"

tagsOverview = true

showProjectsList = false
projectsUrl = "https://github.com/devtty"
colortheme = "devtty"
# css = ["css/styles.css"]
gravatar = "denis@devtty.de"

showAllPostsArchive = false

[params.author]
name = "denis r."
email = "denis@devtty.de"

[params.header.title]
name = "devtty"
pre = "<i class='far fa-grin-tongue-wink' aria-hidden='true'></i>"

[params.footer]
enable = true
hugo = true
author = false
license = 'Denis Renning | <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.home]
  [params.home.profile]
  enable = true
  gravatarEmail = "denis@devtty.de"
  title = "Hiya!"
  subtitle = "I’m Denis - currently software engineer and specialized on web applications and IT security."
  typeit = false
  social = true

[markup.goldmark.renderer]
  unsafe = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params.page.share]
enable = true
X = false
Weibo = false

[params.social]
GitHub = "devtty"
Instagram = "dev_tty"
#Keybase="devtty"
#Bandcamp="sad"
#Steam="hosenscheisser"
Bluesky = "devtty.de"
Email ="denis@devtty.de"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

