#+TITLE: At the university... again
#+DATE: 2021-04-10
#+DRAFT: false
#+TAGS[]: university

Don’t know if midlife-crisis hits me hard yet – or something else – but now I’m officially a student again. It’s (nearly) the same course of studies as twenty years ago and if I read the module handbook I find a lot of similarities. But as I said – 20 yrs – a lot of time, a lot of changes and I’m really a little bit afraid of the things to come.

* But why?

I don’t want to know how much money my employer (me too) spent on further education in the last twenty years. But I know that currently there is some kind of standstill. And I know that education at universities in Germany could be much cheaper than private education. Many of the private trainings I had taken in the last years led to an invoice between 1500-2000 € each, by far much more then tuition fee at german (state) universities.

The standstill itself could be characterized as a feeling of standstill – from a personal perspective. Currently I’m working as a software development engineer, architect, project manager, whatever, for several projects and some of these I’m accompanying since more than fifteen years now. I’ll bet you know the feeling that there must be something else? And now I’m here! University student again…

+(the other way would have been to become a barge operator – but there are wife and kids… maybe in another life)+
