#+TITLE: I knew this
#+DATE: 2021-07-14
#+DRAFT: false
#+TAGS[]: university didactics elearning

Really! But I don’t know how and I don’t know in which relation I know things teached here. Media Didactics or didactics in general. Maybe I had some basic knowledge earned in a project or in my diploma thesis days.

Usually I don’t like to work on topics that are so far from my interests. I’m not a teacher, I’m happy when I can fix or create things or solve riddles for myself without bothering others. When I was younger I preferred taking extra hours at night (in the dark… alone!). This course meant team work, with team results and with a team! And I remembered the topic as a little bit dry and boring. At least it was just one multiple choice test and two written concepts to finish this. And writing concepts is something I had done often in past.

I finished that course better than I thought and I have to admit that it’s not just learn, write the exams and forget again. Although I know I have still no ambitions to become a teacher or write great tutorials but I think that I’m able to document better than before.
